# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar10
  - model: resnet50
  - trainer: default
  - paths: default
  - hydra: default

task_name: "prune"

seed: 42

ckpt_path: logs/pre-train/runs/2024-06-26_07-06-44/checkpoints/last.pth
prune_amount: 0.841510680753888
prune_steps: 1
prune_type: "global_unstructured"
