# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar10
  - model: lenet5
  - trainer: default
  - paths: default
  - hydra: default

task_name: "pre-train"

seed: 42

ckpt_path: logs/pre-train/runs/2024-06-26_04-08-33/checkpoints/last.pth
prune_amount: 0.8415106807538887
prune_steps: 1
prune_type: "unstructed"
